name: Publish

on:
  release:
    types: [published]

jobs:
  npm-publish:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - uses: actions/setup-node@v1
        with:
          node-version: 12
          registry-url: https://registry.npmjs.org/
      - run: yarn install
      - run: npm publish --access public
        env:
          NODE_AUTH_TOKEN: ${{secrets.NPM_AUTH_TOKEN}}
  docker-publish:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Publish Docker
      uses: elgohr/Publish-Docker-Github-Action@2.12
      with:
        name: restqa/restqa
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}
        tags: "latest,${{ github.event.release.tag_name }}"
  discord-notify:
    runs-on: ubuntu-latest
    steps:
      - name: Discord notification
        env:
          DISCORD_WEBHOOK: ${{ secrets.DISCORD_WEBHOOK }}
          DISCORD_EMBEDS: |
            [{
              "title": "Version  ${{ github.event.release.tag_name }}  has been released :tada::tada::tada:",
              "description": "[CHANGELOG](https://github.com/restqa/restqa/blob/${{ github.event.release.tag_name }}/CHANGELOG.md) available\n\nDo not forget to update your local RestQA version using the command:\n```\n$ npm i -g @restqa/restqa@latest\n```",
              "url": "http://google.com",
              "color": 11032831
             }]
        uses: Ilshidur/action-discord@master
